
# Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: holic

# Site settings
title: monorholic
logo: "/assets/images/monorholic_t.png"
description: monorholic dev blog
email: monorholic@gmail.com
twitter_username:  monorholic
github_username:  monorholic
search: true
repository: "monorholic/monorholic"
include: ["_pages"]
permalink: /:title/
markdown: kramdown
paginate: 6
paginate_path: /page:num/
timezone: Asia/Seoul

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "monorholic"
  avatar : "/assets/images/monorholic_w.png"
  bio    : "monorholic"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/monorholic"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/monorholic"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/monorholic"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/monorholic"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

exclude: [Gemfile, Gruntfile.lock, README.md, serve.bat]

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
